from PyQt5 import QtCore, QtGui, QtWidgets

QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)
QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 800)
        MainWindow.setMinimumSize(QtCore.QSize(900, 800))
        MainWindow.setMaximumSize(QtCore.QSize(900, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 20, 861, 751))
        self.stackedWidget.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.welcome_box1 = QtWidgets.QLabel(self.home_page)
        self.welcome_box1.setGeometry(QtCore.QRect(100, 50, 710, 150))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.welcome_box1.setFont(font)
        self.welcome_box1.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_box1.setWordWrap(True)
        self.welcome_box1.setObjectName("welcome_box1")
        self.welcome_box2 = QtWidgets.QLabel(self.home_page)
        self.welcome_box2.setGeometry(QtCore.QRect(100, 200, 710, 20))
        self.welcome_box2.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_box2.setObjectName("welcome_box2")
        self.label = QtWidgets.QLabel(self.home_page)
        self.label.setGeometry(QtCore.QRect(305, 320, 300, 361))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.Playbutton = QtWidgets.QPushButton(self.home_page, clicked=lambda: self.play())
        self.Playbutton.setGeometry(QtCore.QRect(60, 300, 131, 121))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.Playbutton.setFont(font)
        self.Playbutton.setObjectName("Playbutton")
        self.Previousbutton = QtWidgets.QPushButton(self.home_page, clicked=lambda: self.previousscores())
        self.Previousbutton.setGeometry(QtCore.QRect(640, 300, 210, 120))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Previousbutton.setFont(font)
        self.Previousbutton.setObjectName("Previousbutton")
        self.stackedWidget.addWidget(self.home_page)
        self.game_page = QtWidgets.QWidget()
        self.game_page.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.game_page.setObjectName("game_page")
        self.Message_box = QtWidgets.QPlainTextEdit(self.game_page)
        self.Message_box.setGeometry(QtCore.QRect(130, 540, 560, 200))
        self.Message_box.setMinimumSize(QtCore.QSize(560, 200))
        self.Message_box.setMaximumSize(QtCore.QSize(560, 200))
        self.Message_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Message_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Message_box.setBackgroundVisible(False)
        self.Message_box.setObjectName("Message_box")
        self.Player_wins = QtWidgets.QLineEdit(self.game_page)
        self.Player_wins.setGeometry(QtCore.QRect(130, 480, 200, 30))
        self.Player_wins.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Player_wins.setObjectName("Player_wins")
        self.Computer_wins = QtWidgets.QLineEdit(self.game_page)
        self.Computer_wins.setGeometry(QtCore.QRect(490, 480, 200, 30))
        self.Computer_wins.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Computer_wins.setObjectName("Computer_wins")
        self.Spockbutton = QtWidgets.QPushButton(self.game_page, clicked=lambda: self.spockpush())
        self.Spockbutton.setGeometry(QtCore.QRect(630, 250, 200, 200))
        self.Spockbutton.setMinimumSize(QtCore.QSize(200, 200))
        self.Spockbutton.setMaximumSize(QtCore.QSize(200, 200))
        self.Spockbutton.setIcon(QtGui.QIcon("Spock.jpg"))
        self.Spockbutton.setIconSize(QtCore.QSize(190, 190))
        self.Spockbutton.setText("")
        self.Spockbutton.setObjectName("Spockbutton")
        self.Scissorsbutton = QtWidgets.QPushButton(self.game_page, clicked=lambda: self.scissorpush())
        self.Scissorsbutton.setGeometry(QtCore.QRect(630, 20, 200, 200))
        self.Scissorsbutton.setMinimumSize(QtCore.QSize(200, 200))
        self.Scissorsbutton.setMaximumSize(QtCore.QSize(200, 200))
        self.Scissorsbutton.setIcon(QtGui.QIcon("Scissors.jpg"))
        self.Scissorsbutton.setIconSize(QtCore.QSize(190, 190))
        self.Scissorsbutton.setText("")
        self.Scissorsbutton.setObjectName("Scissorsbutton")
        self.Paperbutton = QtWidgets.QPushButton(self.game_page, clicked=lambda: self.paperpush())
        self.Paperbutton.setGeometry(QtCore.QRect(330, 20, 200, 200))
        self.Paperbutton.setMinimumSize(QtCore.QSize(200, 200))
        self.Paperbutton.setMaximumSize(QtCore.QSize(200, 200))
        self.Paperbutton.setIcon(QtGui.QIcon("Paper.jpg"))
        self.Paperbutton.setIconSize(QtCore.QSize(190, 190))
        self.Paperbutton.setText("")
        self.Paperbutton.setObjectName("Paperbutton")
        self.Lizardbutton = QtWidgets.QPushButton(self.game_page, clicked=lambda: self.lizardpush())
        self.Lizardbutton.setGeometry(QtCore.QRect(40, 250, 200, 200))
        self.Lizardbutton.setMinimumSize(QtCore.QSize(200, 200))
        self.Lizardbutton.setMaximumSize(QtCore.QSize(200, 200))
        self.Lizardbutton.setAutoFillBackground(False)
        self.Lizardbutton.setIcon(QtGui.QIcon('Lizard.jpg'))
        self.Lizardbutton.setIconSize(QtCore.QSize(190, 150))
        self.Lizardbutton.setText("")
        self.Lizardbutton.setObjectName("Lizardbutton")
        self.Rockbutton = QtWidgets.QPushButton(self.game_page, clicked=lambda: self.rockpush())
        self.Rockbutton.setGeometry(QtCore.QRect(40, 20, 200, 200))
        self.Rockbutton.setMinimumSize(QtCore.QSize(200, 200))
        self.Rockbutton.setMaximumSize(QtCore.QSize(200, 200))
        self.Rockbutton.setIcon(QtGui.QIcon("Rock.jpg"))
        self.Rockbutton.setIconSize(QtCore.QSize(190, 190))
        self.Rockbutton.setText("")
        self.Rockbutton.setObjectName("Rockbutton")
        self.Computerimage = QtWidgets.QPushButton(self.game_page)
        self.Computerimage.setGeometry(QtCore.QRect(330, 250, 200, 200))
        self.Computerimage.setMinimumSize(QtCore.QSize(200, 200))
        self.Computerimage.setMaximumSize(QtCore.QSize(200, 200))
        self.Computerimage.setIcon(QtGui.QIcon(""))
        self.Computerimage.setIconSize(QtCore.QSize(190, 190))
        self.Computerimage.setText("")
        self.Computerimage.setObjectName("Computerimage")
        self.stackedWidget.addWidget(self.game_page)
        self.resultpage = QtWidgets.QWidget()
        self.resultpage.setStyleSheet("background-color: rgb(170, 85, 127);")
        self.resultpage.setObjectName("resultpage")
        self.Message_box2 = QtWidgets.QPlainTextEdit(self.resultpage)
        self.Message_box2.setGeometry(QtCore.QRect(130, 540, 560, 200))
        self.Message_box2.setMinimumSize(QtCore.QSize(560, 200))
        self.Message_box2.setMaximumSize(QtCore.QSize(560, 200))
        self.Message_box2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Message_box2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Message_box2.setBackgroundVisible(False)
        self.Message_box2.setObjectName("Message_box2")
        self.resultbox = QtWidgets.QLabel(self.resultpage)
        self.resultbox.setGeometry(QtCore.QRect(200, 100, 500, 200))
        font = QtGui.QFont()
        font.setPointSize(44)
        self.resultbox.setFont(font)
        self.resultbox.setText("")
        self.resultbox.setAlignment(QtCore.Qt.AlignCenter)
        self.resultbox.setObjectName("resultbox")
        self.playagain = QtWidgets.QPushButton(self.resultpage, clicked=lambda: self.play())
        self.playagain.setGeometry(QtCore.QRect(100, 340, 200, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.playagain.setFont(font)
        self.playagain.setObjectName("playagain")
        self.homescreen = QtWidgets.QPushButton(self.resultpage, clicked=lambda: self.home())
        self.homescreen.setGeometry(QtCore.QRect(600, 340, 200, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.homescreen.setFont(font)
        self.homescreen.setObjectName("homescreen")
        self.stackedWidget.addWidget(self.resultpage)
        self.stackedWidget.addWidget(self.resultpage)
        self.score_page = QtWidgets.QWidget()
        self.score_page.setStyleSheet("background-color: rgb(170, 170, 0);")
        self.score_page.setObjectName("score_page")
        self.Resetdata_2 = QtWidgets.QPushButton(self.score_page, clicked=lambda: self.reset_data())
        self.Resetdata_2.setGeometry(QtCore.QRect(10, 620, 200, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Resetdata_2.setFont(font)
        self.Resetdata_2.setObjectName("Resetdata_2")
        self.homescreen_2 = QtWidgets.QPushButton(self.score_page, clicked=lambda: self.home())
        self.homescreen_2.setGeometry(QtCore.QRect(640, 620, 200, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.homescreen_2.setFont(font)
        self.homescreen_2.setObjectName("homescreen_2")
        self.score_box = QtWidgets.QLabel(self.score_page)
        self.score_box.setGeometry(QtCore.QRect(30, 50, 810, 550))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.score_box.setFont(font)
        self.score_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.score_box.setText("")
        self.score_box.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.score_box.setObjectName("score_box")
        self.stackedWidget.addWidget(self.score_page)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ProjectPart2"))
        self.welcome_box1.setText(
            _translate("MainWindow", "<html><head/><body><p>Rock Paper Scissors Lizard Spock</p></body></html>"))
        self.welcome_box2.setText(_translate("MainWindow", "As seen on The Big Bang Theory"))
        self.label.setText(_translate("MainWindow",
                                      "<html><head/><body><p>The rules are simple:</p><p>Scissors cut paper, paper covers rock, rock crushes lizard, lizard poisons Spock, Spock smashes scissors, scissors decapitate lizard, lizard eats paper, paper disproves Spock, Spock vaporizes rock, and as it always has, rock crushes scissors.</p><p>Press \'Play\' to challenge the computer or \'Previous Scores\' to see a running total of wins and statistics.</p></body></html>"))
        self.Playbutton.setText(_translate("MainWindow", "Play"))
        self.Previousbutton.setText(_translate("MainWindow", "Previous Scores"))
        self.playagain.setText(_translate("MainWindow", "Play again?"))
        self.homescreen.setText(_translate("MainWindow", "Home"))
        self.Resetdata_2.setText(_translate("MainWindow", "Reset Data"))
        self.homescreen_2.setText(_translate("MainWindow", "Home"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
